services:
  db:
    image: mysql:5.7
    container_name: omeka_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  omeka:
    build: ./apache-php
    container_name: omeka_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./omeka:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

volumes:
  db_data: